-- Run this file directly in MySQL; no Laravel migration is required.
CREATE TABLE IF NOT EXISTS `appointments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `patient_name` VARCHAR(255) NULL,
  `phone` VARCHAR(20) NOT NULL,
  `appointment_date` DATE NOT NULL,
  `jalali_year` SMALLINT UNSIGNED NOT NULL,
  `jalali_month` TINYINT UNSIGNED NOT NULL,
  `jalali_day` TINYINT UNSIGNED NOT NULL,
  `appointment_time` TIME NOT NULL,
  `status` ENUM('scheduled','completed','cancelled') NOT NULL DEFAULT 'scheduled',
  `notes` VARCHAR(1000) NULL,
  `reminder_at` DATETIME NULL,
  `reminder_sent_at` DATETIME NULL,
  `reminder_locked_at` DATETIME NULL,
  `reminder_last_attempt_at` DATETIME NULL,
  `reminder_attempts` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `reminder_error` VARCHAR(500) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `appointments_month_day_index` (`jalali_year`,`jalali_month`,`jalali_day`),
  KEY `appointments_date_time_index` (`appointment_date`,`appointment_time`),
  KEY `appointments_phone_index` (`phone`),
  KEY `appointments_user_id_index` (`user_id`),
  KEY `appointments_reminder_due_index` (`status`,`reminder_sent_at`,`reminder_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
